version: '3.4'

services:
  exercisedb:
    container_name: exercisedb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=exercisedb
      - MYSQL_USER=filipe
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
      
  exercises.api:
    container_name: exercise.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=server=db:5200; database=exercisedb; persistsecurityinfo=True; user id=filipe; password=password"
    depends_on:
      - exercisedb
    ports:
      - "8000:80"
