version: '3.4'

services:
  exercisedb:
    container_name: exercisedb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
  exercises.api:
    container_name: exercise.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://exercisedb:27017"
    depends_on:
      - exercisedb
    ports:
      - "8000:80"
