version: '3.4'

services:
  exercisedb:
    container_name: exercisedb
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
        - 3306:3306
    volumes:
        - mysql_data:/var/lib/mysql

  exercises.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings:OrderingConnectionString=server=exercisedb;port=3306;database=exercisedb;persistsecurityinfo=True;user id=root;password=P@ssw0rd"
    ports:
        - "8000:80"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro