version: '3.4'

services:
  exercisedb:
    image: mysql

  adminer:
    image: adminer

  portainer:
    image: portainer/portainer-ce

  exercises.api:
    image: ${DOCKER_REGISTRY-}exercisesapi
    build:
      context: .
      dockerfile: Services/Exercises/Exercises.API/Dockerfile
  
  musclegroups.api:
    image: ${DOCKER_REGISTRY-}musclegroupsapi
    build:
      context: .
      dockerfile: Services/MuscleGroup/MuscleGroup.API/Dockerfile

volumes:
  mysql_data:
  portainer_data:
