version: '3.4'

services:
  exercisedb:
    image: mysql

  portainer:
    image: portainer/portainer-ce

  exercises.api:
    image: ${DOCKER_REGISTRY-}exercisesapi
    build:
      context: .
      dockerfile: Services/Exercises/Exercises.API/Dockerfile
  
volumes:
  mysql_data:
  portainer_data: